/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.onkiup.restian; 
import java.util.Collection;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;


public class Restian  { //implements HttpHandler {
//  private HttpServer server;
//  private Set<Api> apis;
//
//
//  public Restian add(Api api) {
//    apis.add(api);
//    return this;
//  }
//
//  public Restian remove(Api api) {
//    apis.remove(api);
//    return this;
//  }
//
//  @Override
//  public void handle(HttpExchange exchange) {
//    try {
//      Class<? extends Entity> target = null;
//      Api api = route(exchange);
//      if (api != null) {
//        ApiResponse response = delegate(api, exchange);
//        Serializer serializer = api.serializer();
//        serializer.serialize(exchange, response);
//      } else {
//        throw new NoSuchRoute();
//      }
//    } catch (HttpError he) {
//      // TODO: proper error reporting
//      throw new RuntimeException(he);
//    }
//  }
//
//
//  private Api route(HttpExchange exchange) {
//    String path = exchange.getRequestURI().getPath();
//    return apis.stream()
//      .filter(api -> path.startsWith(api.baseUrl()))
//      .filter(Objects::nonNull)
//      .findFirst()
//      .orElse(null);
//  }
//
//  private ApiResponse delegate(Api api, HttpExchange exchange) throws HttpError {
//    EntityRouter router = api.router();
//    Endpoint target = router.route(exchange);
//    EntityManager manager = api.entityManager();
//
//    QueryStringParser parser = api.queryParser();
//    ApiQuery query = parser.parse(endpoint, exchange);
//
//    api.authValidator().authorize(query);
//    if (query.authorization() == null) {
//      throw new Unauthorized();
//    }
//
//    return query.operation().execute(query);
//  }
//
}
